import mongoose from 'mongoose';
import path from 'path';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(__dirname, '../../.env') });
dotenv.config({ path: path.resolve(__dirname, '../.env') });

import {
  Organisation,
  Branch,
  FinancialYear,
  Customer,
  Product,
  Bill,
  Invoice,
  PurchaseOrder,
  StoreItem,
  DeliveryChallan,
  UserAccount,
  Vendor,
  BankAccount,
} from './models/ErpModels';
import { calculateDocumentTaxes } from './utils/taxCalculation';

const MONGO_URI = process.env.MONGO_URI || '';

export async function seedDatabase() {
  if (!MONGO_URI) {
    console.error('MONGO_URI is required for seeding!');
    process.exit(1);
  }

  console.log('Connecting to MongoDB Atlas for seeding...');
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB Atlas!');

  // Clear existing collections
  await Promise.all([
    Organisation.deleteMany({}),
    Branch.deleteMany({}),
    FinancialYear.deleteMany({}),
    Customer.deleteMany({}),
    Product.deleteMany({}),
    Bill.deleteMany({}),
    Invoice.deleteMany({}),
    PurchaseOrder.deleteMany({}),
    StoreItem.deleteMany({}),
    DeliveryChallan.deleteMany({}),
    UserAccount.deleteMany({}),
    Vendor.deleteMany({}),
  ]);
  console.log('Cleaned old records.');

  // 1. Seed Multiple Organisations
  const organisations = await Organisation.insertMany([
    {
      name: 'Smart Enterprise Industries Ltd.',
      cin: 'U29100TN2026PLC089211',
      gstin: '33AAACT1024K1Z8',
      pan: 'AAACT1024K',
      email: 'operations@smarterp.com',
      phone: '+91 44 2839 4910',
      website: 'https://smart.erp.com',
      address: 'Plot 48/A, Industrial Estate, Guindy, Chennai - 600032, Tamil Nadu, India',
    },
    {
      name: 'Smart Nexa Logistics & Supply Chain Ltd.',
      cin: 'U63090MH2026PLC119042',
      gstin: '27AAACN5421M1ZE',
      pan: 'AAACN5421M',
      email: 'supplychain@smartnexa.com',
      phone: '+91 22 6128 4400',
      website: 'https://nexa.smarterp.com',
      address: 'Logistic Tower, Unit 7B, Bandra-Kurla Complex (BKC), Mumbai - 400051, Maharashtra, India',
    },
    {
      name: 'Smart Apex Electronics & Technologies Pvt. Ltd.',
      cin: 'U32109KA2026PTC204891',
      gstin: '29AAACS8892L1Z4',
      pan: 'AAACS8892L',
      email: 'tech@smartapex.com',
      phone: '+91 80 4455 8890',
      website: 'https://apex.smarterp.com',
      address: 'Apex Tech Park, Phase 2, Electronic City, Bengaluru - 560100, Karnataka, India',
    },
  ]);
  const org = organisations[0];
  const org2 = organisations[1];
  const org3 = organisations[2];
  console.log(`✔ Seeded ${organisations.length} Enterprise Organisations.`);

  // 2. Seed Branches (3 physical units per organisation = 9 total)
  const branches = await Branch.insertMany([
    // Org 1: Smart Enterprise Industries Ltd.
    {
      code: 'BR-CHN-01',
      name: 'Chennai Central HQ & Assembly Plant',
      location: 'Guindy, Chennai',
      address: 'Plot 48/A, Industrial Estate, Guindy, Chennai - 600032',
      gstin: '33AAACT1024K1Z8',
      phone: '+91 44 2839 4910',
      isHeadOffice: true,
      organisationId: org._id.toString(),
    },
    {
      code: 'BR-CBE-02',
      name: 'Coimbatore Heavy Fabrication Unit',
      location: 'Peelamedu, Coimbatore',
      address: 'SF 204, Trichy Road, Peelamedu, Coimbatore - 641004',
      gstin: '33AAACT1024K1Z8',
      phone: '+91 422 257 8820',
      isHeadOffice: false,
      organisationId: org._id.toString(),
    },
    {
      code: 'BR-BLR-03',
      name: 'Bengaluru Tech & Distribution Depot',
      location: 'Peenya, Bengaluru',
      address: 'Industrial Suburb, Peenya 2nd Stage, Bengaluru - 560058',
      gstin: '29AAACT1024K1Z2',
      phone: '+91 80 4120 7711',
      isHeadOffice: false,
      organisationId: org._id.toString(),
    },

    // Org 2: Smart Nexa Logistics & Supply Chain Ltd.
    {
      code: 'BR-MUM-01',
      name: 'Mumbai Western Terminal & Container Depot',
      location: 'BKC / Nhava Sheva, Mumbai',
      address: 'Cargo Complex, Sector 18, JNPT Port Road, Navi Mumbai - 400707',
      gstin: '27AAACN5421M1ZE',
      phone: '+91 22 6128 4400',
      isHeadOffice: true,
      organisationId: org2._id.toString(),
    },
    {
      code: 'BR-DEL-02',
      name: 'Delhi-NCR Multimodal Logistics Hub',
      location: 'Okhla Industrial Area, New Delhi',
      address: 'Plot 15, Phase III, Okhla Industrial Area, New Delhi - 110020',
      gstin: '07AAACN5421M1ZC',
      phone: '+91 11 4180 3322',
      isHeadOffice: false,
      organisationId: org2._id.toString(),
    },
    {
      code: 'BR-KOL-03',
      name: 'Kolkata Eastern Port Transit Facility',
      location: 'Garden Reach, Kolkata',
      address: 'Dock Eastern Gate, Circular Garden Reach Road, Kolkata - 700043',
      gstin: '19AAACN5421M1Z8',
      phone: '+91 33 2450 7711',
      isHeadOffice: false,
      organisationId: org2._id.toString(),
    },

    // Org 3: Smart Apex Electronics & Technologies Pvt. Ltd.
    {
      code: 'BR-BLR-11',
      name: 'Bengaluru Silicon Park Fab 1',
      location: 'Electronic City, Bengaluru',
      address: 'Apex Tech Park, Phase 2, Electronic City, Bengaluru - 560100',
      gstin: '29AAACS8892L1Z4',
      phone: '+91 80 4455 8890',
      isHeadOffice: true,
      organisationId: org3._id.toString(),
    },
    {
      code: 'BR-PUN-01',
      name: 'Pune Precision Micro-Hardware Plant',
      location: 'Hinjawadi Phase 1, Pune',
      address: 'MIDC Knowledge Park, Hinjawadi, Pune - 411057',
      gstin: '27AAACS8892L1Z9',
      phone: '+91 20 6790 2200',
      isHeadOffice: false,
      organisationId: org3._id.toString(),
    },
    {
      code: 'BR-HYD-01',
      name: 'Hyderabad Microelectronics Campus',
      location: 'HITEC City, Hyderabad',
      address: 'Silicon Tower, Madhapur, HITEC City, Hyderabad - 500081',
      gstin: '36AAACS8892L1Z0',
      phone: '+91 40 4880 1199',
      isHeadOffice: false,
      organisationId: org3._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${branches.length} Branches across ${organisations.length} Organisations.`);

  // 3. Seed Financial Years for all Organisations
  const fyList = [];
  for (const o of organisations) {
    fyList.push(
      {
        yearName: '2024-2025',
        startDate: '2024-04-01',
        endDate: '2025-03-31',
        isCurrent: false,
        status: 'Closed',
        organisationId: o._id.toString(),
      },
      {
        yearName: '2025-2026',
        startDate: '2025-04-01',
        endDate: '2026-03-31',
        isCurrent: false,
        status: 'Active',
        organisationId: o._id.toString(),
      },
      {
        yearName: '2026-2027',
        startDate: '2026-04-01',
        endDate: '2027-03-31',
        isCurrent: true,
        status: 'Active',
        organisationId: o._id.toString(),
      }
    );
  }
  const financialYears = await FinancialYear.insertMany(fyList);
  console.log(`✔ Seeded ${financialYears.length} Financial Years across all organisations.`);

  // 4. Seed Users with multi-organisation and multi-branch role mappings
  const users = await UserAccount.insertMany([
    {
      email: 'jay.raam@smart.com',
      mobile: '9840199882',
      passwordHash: 'password123',
      name: 'Jay Raam',
      role: 'SuperAdmin',
      branchId: branches[0]._id.toString(),
      branchName: branches[0].name,
      organisationId: org._id.toString(),
      roles: [
        // Org 1 roles
        {
          organisationId: org._id.toString(),
          organisationName: org.name,
          branchId: branches[0]._id.toString(),
          branchName: branches[0].name,
          roleName: 'SuperAdmin',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org._id.toString(),
          organisationName: org.name,
          branchId: branches[1]._id.toString(),
          branchName: branches[1].name,
          roleName: 'Operations Director',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org._id.toString(),
          organisationName: org.name,
          branchId: branches[2]._id.toString(),
          branchName: branches[2].name,
          roleName: 'Executive Supervisor',
          userType: 'SuperAdmin',
        },
        // Org 2 roles
        {
          organisationId: org2._id.toString(),
          organisationName: org2.name,
          branchId: branches[3]._id.toString(),
          branchName: branches[3].name,
          roleName: 'Managing Director',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org2._id.toString(),
          organisationName: org2.name,
          branchId: branches[4]._id.toString(),
          branchName: branches[4].name,
          roleName: 'Regional Logistics Head',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org2._id.toString(),
          organisationName: org2.name,
          branchId: branches[5]._id.toString(),
          branchName: branches[5].name,
          roleName: 'Port Operations Overseer',
          userType: 'SuperAdmin',
        },
        // Org 3 roles
        {
          organisationId: org3._id.toString(),
          organisationName: org3.name,
          branchId: branches[6]._id.toString(),
          branchName: branches[6].name,
          roleName: 'Principal Executive',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org3._id.toString(),
          organisationName: org3.name,
          branchId: branches[7]._id.toString(),
          branchName: branches[7].name,
          roleName: 'Hardware Fab Board',
          userType: 'SuperAdmin',
        },
        {
          organisationId: org3._id.toString(),
          organisationName: org3.name,
          branchId: branches[8]._id.toString(),
          branchName: branches[8].name,
          roleName: 'Technology Director',
          userType: 'SuperAdmin',
        },
      ],
    },
    {
      email: 'admin@smart.com',
      mobile: '9840155555',
      passwordHash: 'password123',
      name: 'Operations Admin',
      role: 'Admin',
      branchId: branches[0]._id.toString(),
      branchName: branches[0].name,
      organisationId: org._id.toString(),
      roles: [
        {
          organisationId: org._id.toString(),
          organisationName: org.name,
          branchId: branches[0]._id.toString(),
          branchName: branches[0].name,
          roleName: 'Operations Admin',
          userType: 'Admin',
        },
        {
          organisationId: org2._id.toString(),
          organisationName: org2.name,
          branchId: branches[3]._id.toString(),
          branchName: branches[3].name,
          roleName: 'Supply Chain Admin',
          userType: 'Admin',
        },
      ],
    },
    {
      email: 'priya.sharma@smart.com',
      mobile: '9840112345',
      passwordHash: 'password123',
      name: 'Priya Sharma',
      role: 'Manager',
      branchId: branches[1]._id.toString(),
      branchName: branches[1].name,
      organisationId: org._id.toString(),
      roles: [
        {
          organisationId: org._id.toString(),
          organisationName: org.name,
          branchId: branches[1]._id.toString(),
          branchName: branches[1].name,
          roleName: 'Plant Manager',
          userType: 'Manager',
        },
      ],
    },
    {
      email: 'vikram.seth@smartnexa.com',
      mobile: '9820011884',
      passwordHash: 'password123',
      name: 'Vikram Seth',
      role: 'Manager',
      branchId: branches[3]._id.toString(),
      branchName: branches[3].name,
      organisationId: org2._id.toString(),
      roles: [
        {
          organisationId: org2._id.toString(),
          organisationName: org2.name,
          branchId: branches[3]._id.toString(),
          branchName: branches[3].name,
          roleName: 'Logistics Terminal VP',
          userType: 'Manager',
        },
      ],
    },
    {
      email: 'ananya.rao@smartapex.com',
      mobile: '9845019283',
      passwordHash: 'password123',
      name: 'Ananya Rao',
      role: 'Manager',
      branchId: branches[6]._id.toString(),
      branchName: branches[6].name,
      organisationId: org3._id.toString(),
      roles: [
        {
          organisationId: org3._id.toString(),
          organisationName: org3.name,
          branchId: branches[6]._id.toString(),
          branchName: branches[6].name,
          roleName: 'Fab 1 Semiconductor Director',
          userType: 'Manager',
        },
      ],
    },
  ]);
  console.log(`✔ Seeded ${users.length} Multi-Org User Accounts.`);

  // 5. Seed Customers (Organisation level with branch assignment)
  const customers = await Customer.insertMany([
    {
      code: 'CUST-TATA',
      name: 'Tata Motors Limited',
      contactPerson: 'Ramesh Sundaram (VP Procurement)',
      email: 'ramesh.sundaram@tatamotors.com',
      phone: '+91 98401 23890',
      address: 'Pimpri Industrial Area, Sector 4, Pune - 411018, Maharashtra',
      billingAddress: 'Pimpri Industrial Area, Sector 4, Pune - 411018, Maharashtra',
      shippingAddress: 'Plot 12, SIPCOT Industrial Park, Sriperumbudur, Kanchipuram - 602105, Tamil Nadu',
      city: 'Pune / Chennai',
      state: 'Maharashtra',
      billingState: 'Maharashtra',
      shippingState: 'Tamil Nadu',
      gstin: '27AAACT2727Q1ZW',
      outstandingBalance: 1450000,
      creditLimit: 5000000,
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
      addresses: [
        {
          type: 'BILLING',
          attention: 'Accounts Payable Dept',
          addressLine1: 'Pimpri Industrial Area, Sector 4',
          addressLine2: 'Near Old Mumbai-Pune Highway',
          city: 'Pune',
          state: 'Maharashtra',
          pincode: '411018',
          country: 'India',
          phone: '+91 98401 23890',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'BILLING',
          attention: 'Central Billing Hub (Previous Office)',
          addressLine1: 'Bombay House, 24 Homi Mody Street',
          addressLine2: 'Fort',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400001',
          country: 'India',
          phone: '+91 22 6665 8282',
          isActive: false,
          createdAt: new Date('2025-01-10'),
        },
        {
          type: 'SHIPPING',
          attention: 'Assembly Logistics Incharge',
          addressLine1: 'Plot 12, SIPCOT Industrial Park',
          addressLine2: 'Sriperumbudur Phase II',
          city: 'Kanchipuram',
          state: 'Tamil Nadu',
          pincode: '602105',
          country: 'India',
          phone: '+91 98401 23890',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'SHIPPING',
          attention: 'Central Transit Hub (Decommissioned)',
          addressLine1: 'Warehousing Bay 8, Pimpri Works',
          addressLine2: 'Sector 2',
          city: 'Pune',
          state: 'Maharashtra',
          pincode: '411018',
          country: 'India',
          phone: '+91 98401 23890',
          isActive: false,
          createdAt: new Date('2025-02-15'),
        },
      ],
    },
    {
      code: 'CUST-LT',
      name: 'Larsen & Toubro Heavy Engineering',
      contactPerson: 'Ananya Deshmukh (Lead Project Engg)',
      email: 'ananya.d@lntecc.com',
      phone: '+91 97890 54321',
      address: 'L&T House, Ballard Estate, Mumbai - 400001, Maharashtra',
      billingAddress: 'L&T House, Ballard Estate, Mumbai - 400001, Maharashtra',
      shippingAddress: 'L&T Heavy Engineering Complex, Eachanari, Coimbatore - 641021, Tamil Nadu',
      city: 'Mumbai / Coimbatore',
      state: 'Maharashtra',
      billingState: 'Maharashtra',
      shippingState: 'Tamil Nadu',
      gstin: '27AAACL0149C1ZM',
      outstandingBalance: 820000,
      creditLimit: 3000000,
      organisationId: org._id.toString(),
      branchId: branches[1]._id.toString(),
      addresses: [
        {
          type: 'BILLING',
          attention: 'Tax & Compliance Group',
          addressLine1: 'L&T House, Ballard Estate',
          addressLine2: 'Narottam Morarjee Marg',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400001',
          country: 'India',
          phone: '+91 97890 54321',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'SHIPPING',
          attention: 'Store Receiving Division',
          addressLine1: 'L&T Heavy Engineering Complex',
          addressLine2: 'Eachanari Post',
          city: 'Coimbatore',
          state: 'Tamil Nadu',
          pincode: '641021',
          country: 'India',
          phone: '+91 97890 54321',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
      ],
    },
    {
      code: 'CUST-BHEL',
      name: 'Bharat Heavy Electricals Ltd (BHEL)',
      contactPerson: 'K. Balasubramanian (AGM Supply Chain)',
      email: 'k.bala@bhel.in',
      phone: '+91 94440 98765',
      address: 'High Pressure Boiler Plant, Tiruchirappalli - 620014, Tamil Nadu',
      billingAddress: 'High Pressure Boiler Plant, Tiruchirappalli - 620014, Tamil Nadu',
      shippingAddress: 'Central Stores, Unit 2, BHEL Complex, Trichy - 620014, Tamil Nadu',
      city: 'Trichy',
      state: 'Tamil Nadu',
      billingState: 'Tamil Nadu',
      shippingState: 'Tamil Nadu',
      gstin: '33AAACB4146P1ZL',
      outstandingBalance: 420000,
      creditLimit: 2500000,
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
      addresses: [
        {
          type: 'BILLING',
          attention: 'Finance & Accounts Division',
          addressLine1: 'High Pressure Boiler Plant',
          addressLine2: 'Post Box No. 14, Thiruverumbur',
          city: 'Tiruchirappalli',
          state: 'Tamil Nadu',
          pincode: '620014',
          country: 'India',
          phone: '+91 94440 98765',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'SHIPPING',
          attention: 'Central Stores Incharge Unit 2',
          addressLine1: 'Central Stores, Unit 2, BHEL Complex',
          addressLine2: 'Boiler Fabrication Area',
          city: 'Tiruchirappalli',
          state: 'Tamil Nadu',
          pincode: '620014',
          country: 'India',
          phone: '+91 94440 98765',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
      ],
    },
    {
      code: 'CUST-ASHOK',
      name: 'Ashok Leyland Defence & Commercial',
      contactPerson: 'Siddharth Varma (DGM Ops)',
      email: 'siddharth.v@ashokleyland.com',
      phone: '+91 99620 11223',
      address: 'No 1, Sardar Patel Road, Guindy, Chennai - 600032, Tamil Nadu',
      billingAddress: 'No 1, Sardar Patel Road, Guindy, Chennai - 600032, Tamil Nadu',
      shippingAddress: 'Plant II, Ennore High Road, Chennai - 600057, Tamil Nadu',
      city: 'Chennai',
      state: 'Tamil Nadu',
      billingState: 'Tamil Nadu',
      shippingState: 'Tamil Nadu',
      gstin: '33AAACA1991F1Z1',
      outstandingBalance: 2100000,
      creditLimit: 6000000,
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
      addresses: [
        {
          type: 'BILLING',
          attention: 'Commercial Billing Desk',
          addressLine1: 'No 1, Sardar Patel Road',
          addressLine2: 'Guindy',
          city: 'Chennai',
          state: 'Tamil Nadu',
          pincode: '600032',
          country: 'India',
          phone: '+91 99620 11223',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'BILLING',
          attention: 'Old Corporate Office (Historical)',
          addressLine1: '19 Rajaji Salai',
          addressLine2: 'Parrys Corner',
          city: 'Chennai',
          state: 'Tamil Nadu',
          pincode: '600001',
          country: 'India',
          phone: '+91 44 2534 1234',
          isActive: false,
          createdAt: new Date('2024-11-20'),
        },
        {
          type: 'SHIPPING',
          attention: 'Plant II Receiving Yard',
          addressLine1: 'Plant II, Ennore High Road',
          addressLine2: 'Kathivakkam, Ennore',
          city: 'Chennai',
          state: 'Tamil Nadu',
          pincode: '600057',
          country: 'India',
          phone: '+91 99620 11223',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'SHIPPING',
          attention: 'Hosur Plant I Depot (Alternative Hub)',
          addressLine1: 'Plot 77, SIPCOT Phase 1',
          addressLine2: 'Mookandapalli',
          city: 'Hosur',
          state: 'Tamil Nadu',
          pincode: '635126',
          country: 'India',
          phone: '+91 4344 276500',
          isActive: false,
          createdAt: new Date('2025-08-10'),
        },
      ],
    },
    {
      code: 'CUST-RELIANCE',
      name: 'Reliance Petrochemicals Jamnagar',
      contactPerson: 'Hardik Patel (Head Material)',
      email: 'hardik.patel@ril.com',
      phone: '+91 98250 88771',
      address: 'Village Motikhavdi, Digvijaygram, Jamnagar - 361140, Gujarat',
      billingAddress: 'Village Motikhavdi, Digvijaygram, Jamnagar - 361140, Gujarat',
      shippingAddress: 'Despatch Bay 4, Refinery Site, Jamnagar - 361140, Gujarat',
      city: 'Jamnagar',
      state: 'Gujarat',
      billingState: 'Gujarat',
      shippingState: 'Gujarat',
      gstin: '24AAACR5055K1Z4',
      outstandingBalance: 3400000,
      creditLimit: 8000000,
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
      addresses: [
        {
          type: 'BILLING',
          attention: 'Accounts Commercial Division',
          addressLine1: 'Village Motikhavdi, Digvijaygram',
          addressLine2: 'Refinery Division HQ',
          city: 'Jamnagar',
          state: 'Gujarat',
          pincode: '361140',
          country: 'India',
          phone: '+91 98250 88771',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
        {
          type: 'SHIPPING',
          attention: 'Despatch Bay 4 Supervisor',
          addressLine1: 'Despatch Bay 4, Refinery Complex',
          addressLine2: 'Motikhavdi Main Gate',
          city: 'Jamnagar',
          state: 'Gujarat',
          pincode: '361140',
          country: 'India',
          phone: '+91 98250 88771',
          isActive: true,
          createdAt: new Date('2026-04-01'),
        },
      ],
    },
  ]);
  console.log(`✔ Seeded ${customers.length} Customers.`);

  // 5B. Seed Vendors
  const vendors = await Vendor.insertMany([
    {
      code: 'VEND-MIDH-1',
      name: 'Midhani Metallurgical Alloys Ltd',
      contactPerson: 'V. Sundaram',
      email: 'sales@midhani-india.in',
      phone: '+91 40 2434 0001',
      address: 'PO Kanchanbagh, Hyderabad - 500058',
      city: 'Hyderabad',
      state: 'Telangana',
      gstin: '36AAACM2091J1ZB',
      pan: 'AAACM2091J',
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      code: 'VEND-HERA-2',
      name: 'Heraeus Precious Metals India',
      contactPerson: 'Rajesh Kulkarni',
      email: 'info.metals@heraeus.in',
      phone: '+91 22 6710 4000',
      address: 'Plot A-14, Road No 16, Thane Industrial Area, Mumbai - 400604',
      city: 'Mumbai',
      state: 'Maharashtra',
      gstin: '27AAACH1249K1ZZ',
      pan: 'AAACH1249K',
      organisationId: org._id.toString(),
      branchId: branches[1]._id.toString(),
    },
    {
      code: 'VEND-ADOR-3',
      name: 'Ador Welding Power Systems',
      contactPerson: 'M. Senthil',
      email: 'support@adorwelding.com',
      phone: '+91 44 2625 3311',
      address: 'Plot 72, Ambattur Industrial Estate, Chennai - 600058',
      city: 'Chennai',
      state: 'Tamil Nadu',
      gstin: '33AAACA0853N1ZT',
      pan: 'AAACA0853N',
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${vendors.length} Vendors.`);

  // 6. Seed Products
  const products = await Product.insertMany([
    {
      sku: 'SMART-MMO-101',
      name: 'Titanium MMO Tubular Anode (25mm x 1000mm)',
      hsnCode: '84199090',
      category: 'Titanium Anodes',
      uom: 'Nos',
      sellingPrice: 18500,
      purchaseCost: 11200,
      currentStock: 145,
      minReorderLevel: 30,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      sku: 'SMART-CP-202',
      name: 'Mixed Metal Oxide Ribbon Anode Mesh (6.35mm)',
      hsnCode: '84199090',
      category: 'Cathodic Protection',
      uom: 'Mtr',
      sellingPrice: 4200,
      purchaseCost: 2600,
      currentStock: 820,
      minReorderLevel: 150,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[1]._id.toString(),
    },
    {
      sku: 'SMART-PLT-303',
      name: 'Platinized Titanium Mesh Anode Grade 1',
      hsnCode: '71101100',
      category: 'Titanium Anodes',
      uom: 'Nos',
      sellingPrice: 48000,
      purchaseCost: 32000,
      currentStock: 42,
      minReorderLevel: 10,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      sku: 'SMART-PWR-404',
      name: 'Automatic Cathodic Protection TR Unit 50V/50A',
      hsnCode: '85044090',
      category: 'Electronics & Control',
      uom: 'Nos',
      sellingPrice: 125000,
      purchaseCost: 85000,
      currentStock: 18,
      minReorderLevel: 5,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      sku: 'SMART-RAW-505',
      name: 'ASTM B265 Grade 1 Titanium Sheet 3.0mm',
      hsnCode: '81089010',
      category: 'Raw Materials',
      uom: 'Kg',
      sellingPrice: 3800,
      purchaseCost: 2900,
      currentStock: 1250,
      minReorderLevel: 300,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      sku: 'SMART-FLG-606',
      name: 'Titanium ANSI B16.5 Slip-On Flange 2" Class 150',
      hsnCode: '81089090',
      category: 'Flanges & Fittings',
      uom: 'Nos',
      sellingPrice: 8500,
      purchaseCost: 5200,
      currentStock: 64,
      minReorderLevel: 20,
      taxRate: 18,
      approvalStatus: 'Approved',
      approvedBy: 'Jay Raam',
      approvedAt: new Date(),
      organisationId: org._id.toString(),
      branchId: branches[1]._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${products.length} Products.`);

  // 7. Seed Invoices (with calculated GST, HSN, line items, shipping charges, and addresses)
  const inv1Items = [
    {
      productId: products[2]._id.toString(),
      productName: products[2].name,
      hsnCode: products[2].hsnCode,
      quantity: 6,
      uom: products[2].uom,
      unitPrice: 48000,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const inv1Tax = calculateDocumentTaxes({
    items: inv1Items,
    customerState: customers[2].billingState || 'Tamil Nadu',
    customerGstin: customers[2].gstin,
    shippingCharge: 850,
  });

  const inv2Items = [
    {
      productId: products[3]._id.toString(),
      productName: products[3].name,
      hsnCode: products[3].hsnCode,
      quantity: 2,
      uom: products[3].uom,
      unitPrice: 125000,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const inv2Tax = calculateDocumentTaxes({
    items: inv2Items,
    customerState: customers[3].billingState || 'Tamil Nadu',
    customerGstin: customers[3].gstin,
    shippingCharge: 1500,
  });

  const inv3Items = [
    {
      productId: products[1]._id.toString(),
      productName: products[1].name,
      hsnCode: products[1].hsnCode,
      quantity: 250,
      uom: products[1].uom,
      unitPrice: 4200,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const inv3Tax = calculateDocumentTaxes({
    items: inv3Items,
    customerState: customers[1].billingState || 'Maharashtra',
    customerGstin: customers[1].gstin,
    shippingCharge: 2200,
  });

  const invoices = await Invoice.insertMany([
    {
      invoiceNumber: 'INV-2026-001',
      customerId: customers[2]._id.toString(),
      customerName: customers[2].name,
      customerGstin: customers[2].gstin,
      customerState: customers[2].billingState || 'Tamil Nadu',
      billingAddress: customers[2].billingAddress,
      shippingAddress: customers[2].shippingAddress,
      invoiceDate: '2026-09-01',
      dueDate: '2026-09-30',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: inv1Tax.items,
      subtotal: inv1Tax.subtotal,
      shippingCharge: inv1Tax.shippingCharge,
      shippingTax: inv1Tax.shippingTax,
      taxableAmount: inv1Tax.taxableAmount,
      totalDiscount: inv1Tax.totalDiscount,
      gstRate: 18,
      cgstAmount: inv1Tax.cgstAmount,
      sgstAmount: inv1Tax.sgstAmount,
      igstAmount: inv1Tax.igstAmount,
      taxAmount: inv1Tax.totalTax,
      totalAmount: inv1Tax.grandTotal,
      totalInWords: inv1Tax.totalInWords,
      status: 'Paid',
    },
    {
      invoiceNumber: 'INV-2026-002',
      customerId: customers[3]._id.toString(),
      customerName: customers[3].name,
      customerGstin: customers[3].gstin,
      customerState: customers[3].billingState || 'Tamil Nadu',
      billingAddress: customers[3].billingAddress,
      shippingAddress: customers[3].shippingAddress,
      invoiceDate: '2026-09-08',
      dueDate: '2026-10-08',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: inv2Tax.items,
      subtotal: inv2Tax.subtotal,
      shippingCharge: inv2Tax.shippingCharge,
      shippingTax: inv2Tax.shippingTax,
      taxableAmount: inv2Tax.taxableAmount,
      totalDiscount: inv2Tax.totalDiscount,
      gstRate: 18,
      cgstAmount: inv2Tax.cgstAmount,
      sgstAmount: inv2Tax.sgstAmount,
      igstAmount: inv2Tax.igstAmount,
      taxAmount: inv2Tax.totalTax,
      totalAmount: inv2Tax.grandTotal,
      totalInWords: inv2Tax.totalInWords,
      status: 'Pending',
    },
    {
      invoiceNumber: 'INV-2026-003',
      customerId: customers[1]._id.toString(),
      customerName: customers[1].name,
      customerGstin: customers[1].gstin,
      customerState: customers[1].billingState || 'Maharashtra',
      billingAddress: customers[1].billingAddress,
      shippingAddress: customers[1].shippingAddress,
      invoiceDate: '2026-09-05',
      dueDate: '2026-10-05',
      branchId: branches[1]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: inv3Tax.items,
      subtotal: inv3Tax.subtotal,
      shippingCharge: inv3Tax.shippingCharge,
      shippingTax: inv3Tax.shippingTax,
      taxableAmount: inv3Tax.taxableAmount,
      totalDiscount: inv3Tax.totalDiscount,
      gstRate: 18,
      cgstAmount: inv3Tax.cgstAmount,
      sgstAmount: inv3Tax.sgstAmount,
      igstAmount: inv3Tax.igstAmount,
      taxAmount: inv3Tax.totalTax,
      totalAmount: inv3Tax.grandTotal,
      totalInWords: inv3Tax.totalInWords,
      status: 'Pending',
    },
  ]);
  console.log(`✔ Seeded ${invoices.length} Invoices.`);

  // 9. Seed Purchase Orders
  const po1Items = [
    {
      productId: products[4]._id.toString(),
      description: products[4].name,
      hsnCode: products[4].hsnCode,
      qty: 250,
      unit: products[4].uom,
      rate: 2900,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const po1Tax = calculateDocumentTaxes({
    items: po1Items,
    customerState: vendors[0].state || 'Telangana',
    customerGstin: vendors[0].gstin,
  });

  const po2Items = [
    {
      productId: products[2]._id.toString(),
      description: products[2].name,
      hsnCode: products[2].hsnCode,
      qty: 40,
      unit: products[2].uom,
      rate: 30000,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const po2Tax = calculateDocumentTaxes({
    items: po2Items,
    customerState: vendors[1].state || 'Maharashtra',
    customerGstin: vendors[1].gstin,
  });

  const po3Items = [
    {
      productId: products[5]._id.toString(),
      description: products[5].name,
      hsnCode: products[5].hsnCode,
      qty: 75,
      unit: products[5].uom,
      rate: 5200,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const po3Tax = calculateDocumentTaxes({
    items: po3Items,
    customerState: vendors[2].state || 'Tamil Nadu',
    customerGstin: vendors[2].gstin,
  });

  const purchaseOrders = await PurchaseOrder.insertMany([
    {
      poNumber: 'PO-2026-044',
      vendorId: vendors[0]._id.toString(),
      vendorName: vendors[0].name,
      vendorGstin: vendors[0].gstin,
      vendorAddress: vendors[0].address,
      vendorState: vendors[0].state,
      billingAddress: branches[0].address,
      shippingAddress: branches[0].address,
      poDate: '2026-09-01',
      expectedDate: '2026-09-22',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: po1Tax.items,
      subtotal: po1Tax.subtotal,
      taxableAmount: po1Tax.taxableAmount,
      totalDiscount: po1Tax.totalDiscount,
      cgstAmount: po1Tax.cgstAmount,
      sgstAmount: po1Tax.sgstAmount,
      igstAmount: po1Tax.igstAmount,
      taxAmount: po1Tax.taxAmount,
      totalAmount: po1Tax.totalAmount,
      totalInWords: po1Tax.totalInWords,
      status: 'Approved',
    },
    {
      poNumber: 'PO-2026-045',
      vendorId: vendors[1]._id.toString(),
      vendorName: vendors[1].name,
      vendorGstin: vendors[1].gstin,
      vendorAddress: vendors[1].address,
      vendorState: vendors[1].state,
      billingAddress: branches[1].address,
      shippingAddress: branches[1].address,
      poDate: '2026-09-04',
      expectedDate: '2026-09-29',
      branchId: branches[1]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: po2Tax.items,
      subtotal: po2Tax.subtotal,
      taxableAmount: po2Tax.taxableAmount,
      totalDiscount: po2Tax.totalDiscount,
      cgstAmount: po2Tax.cgstAmount,
      sgstAmount: po2Tax.sgstAmount,
      igstAmount: po2Tax.igstAmount,
      taxAmount: po2Tax.taxAmount,
      totalAmount: po2Tax.totalAmount,
      totalInWords: po2Tax.totalInWords,
      status: 'Pending Approval',
    },
    {
      poNumber: 'PO-2026-046',
      vendorId: vendors[2]._id.toString(),
      vendorName: vendors[2].name,
      vendorGstin: vendors[2].gstin,
      vendorAddress: vendors[2].address,
      vendorState: vendors[2].state,
      billingAddress: branches[0].address,
      shippingAddress: branches[0].address,
      poDate: '2026-08-20',
      expectedDate: '2026-09-05',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
      items: po3Tax.items,
      subtotal: po3Tax.subtotal,
      taxableAmount: po3Tax.taxableAmount,
      totalDiscount: po3Tax.totalDiscount,
      cgstAmount: po3Tax.cgstAmount,
      sgstAmount: po3Tax.sgstAmount,
      igstAmount: po3Tax.igstAmount,
      taxAmount: po3Tax.taxAmount,
      totalAmount: po3Tax.totalAmount,
      totalInWords: po3Tax.totalInWords,
      status: 'Received',
    },
  ]);
  console.log(`✔ Seeded ${purchaseOrders.length} Purchase Orders.`);

  // 9. Seed Bills (PO converted & Direct Bills)
  const bill1Items = [
    {
      productId: products[4]._id.toString(),
      productName: products[4].name,
      hsnCode: products[4].hsnCode,
      quantity: 250,
      uom: products[4].uom,
      unitPrice: 2900,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const bill1Tax = calculateDocumentTaxes({
    items: bill1Items,
    customerState: vendors[0].state || 'Tamil Nadu',
    customerGstin: vendors[0].gstin,
    shippingCharge: 1200,
  });

  const bill2Items = [
    {
      productId: products[2]._id.toString(),
      productName: products[2].name,
      hsnCode: products[2].hsnCode,
      quantity: 4,
      uom: products[2].uom,
      unitPrice: 45000,
      discountPercent: 0,
      taxRate: 18,
    },
  ];
  const bill2Tax = calculateDocumentTaxes({
    items: bill2Items,
    customerState: vendors[1].state || 'Maharashtra',
    customerGstin: vendors[1].gstin,
    shippingCharge: 2500,
  });

  const bills = await Bill.insertMany([
    {
      billNumber: 'BILL-2026-001',
      billDate: '2026-09-06',
      dueDate: '2026-10-06',
      poId: purchaseOrders[0]._id.toString(),
      poNumber: purchaseOrders[0].poNumber,
      vendorId: vendors[0]._id.toString(),
      vendorName: vendors[0].name,
      vendorGstin: vendors[0].gstin,
      vendorState: vendors[0].state || 'Tamil Nadu',
      billingAddress: branches[0].address,
      shippingAddress: branches[0].address,
      items: bill1Tax.items,
      subtotal: bill1Tax.subtotal,
      shippingCharge: bill1Tax.shippingCharge,
      shippingTax: bill1Tax.shippingTax,
      taxableAmount: bill1Tax.taxableAmount,
      cgstAmount: bill1Tax.cgstAmount,
      sgstAmount: bill1Tax.sgstAmount,
      igstAmount: bill1Tax.igstAmount,
      taxAmount: bill1Tax.totalTax,
      totalAmount: bill1Tax.grandTotal,
      totalInWords: bill1Tax.totalInWords,
      status: 'Paid',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
    },
    {
      billNumber: 'BILL-2026-002',
      billDate: '2026-09-10',
      dueDate: '2026-10-10',
      vendorId: vendors[1]._id.toString(),
      vendorName: vendors[1].name,
      vendorGstin: vendors[1].gstin,
      vendorState: vendors[1].state || 'Maharashtra',
      billingAddress: branches[0].address,
      shippingAddress: branches[0].address,
      items: bill2Tax.items,
      subtotal: bill2Tax.subtotal,
      shippingCharge: bill2Tax.shippingCharge,
      shippingTax: bill2Tax.shippingTax,
      taxableAmount: bill2Tax.taxableAmount,
      cgstAmount: bill2Tax.cgstAmount,
      sgstAmount: bill2Tax.sgstAmount,
      igstAmount: bill2Tax.igstAmount,
      taxAmount: bill2Tax.totalTax,
      totalAmount: bill2Tax.grandTotal,
      totalInWords: bill2Tax.totalInWords,
      status: 'Pending',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
    },
  ]);
  console.log(`✔ Seeded ${bills.length} Bills.`);

  // 10. Seed Store Items
  const storeItems = await StoreItem.insertMany([
    {
      productId: products[0]._id.toString(),
      productName: products[0].name,
      sku: products[0].sku,
      warehouse: 'Chennai Central Depot',
      binLocation: 'BIN-A1-04',
      availableStock: 145,
      minLevel: 30,
      maxLevel: 300,
      lastAudited: '2026-09-01',
      status: 'In Stock',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
    },
    {
      productId: products[1]._id.toString(),
      productName: products[1].name,
      sku: products[1].sku,
      warehouse: 'Coimbatore Fabrication Bay',
      binLocation: 'BIN-C2-11',
      availableStock: 820,
      minLevel: 150,
      maxLevel: 1500,
      lastAudited: '2026-09-05',
      status: 'In Stock',
      branchId: branches[1]._id.toString(),
      organisationId: org._id.toString(),
    },
    {
      productId: products[2]._id.toString(),
      productName: products[2].name,
      sku: products[2].sku,
      warehouse: 'Chennai Central Depot',
      binLocation: 'VAULT-SEC-01',
      availableStock: 8,
      minLevel: 10,
      maxLevel: 50,
      lastAudited: '2026-09-08',
      status: 'Low Stock',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
    },
    {
      productId: products[3]._id.toString(),
      productName: products[3].name,
      sku: products[3].sku,
      warehouse: 'Chennai Central Depot',
      binLocation: 'BAY-PWR-02',
      availableStock: 18,
      minLevel: 5,
      maxLevel: 40,
      lastAudited: '2026-09-02',
      status: 'In Stock',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${storeItems.length} Store Items.`);

  // 11. Seed Delivery Challans (Linked directly to Tax Invoices)
  const deliveryChallans = await DeliveryChallan.insertMany([
    {
      dcNumber: 'DC-2026-0041',
      invoiceId: invoices[0]._id.toString(),
      invoiceNumber: invoices[0].invoiceNumber,
      customerId: customers[2]._id.toString(),
      customerName: customers[2].name,
      customerGstin: customers[2].gstin,
      billingAddress: customers[2].billingAddress,
      shippingAddress: customers[2].shippingAddress,
      dispatchDate: '2026-09-10',
      transportMode: 'Dedicated Heavy Truck',
      vehicleNumber: 'TN 09 BY 5521',
      ewayBillNumber: '281099238411',
      driverName: 'R. Murugan',
      driverPhone: '+91 98401 99882',
      items: invoices[0].items,
      status: 'Delivered',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
    },
    {
      dcNumber: 'DC-2026-0042',
      invoiceId: invoices[1]._id.toString(),
      invoiceNumber: invoices[1].invoiceNumber,
      customerId: customers[3]._id.toString(),
      customerName: customers[3].name,
      customerGstin: customers[3].gstin,
      billingAddress: customers[3].billingAddress,
      shippingAddress: customers[3].shippingAddress,
      dispatchDate: '2026-09-12',
      transportMode: 'VRL Logistics Express',
      vehicleNumber: 'KA 01 AH 9942',
      ewayBillNumber: '281099238994',
      driverName: 'S. Kantharaj',
      driverPhone: '+91 97890 12344',
      items: invoices[1].items,
      status: 'In Transit',
      branchId: branches[0]._id.toString(),
      organisationId: org._id.toString(),
      financialYear: '2026-2027',
    },
  ]);
  console.log(`✔ Seeded ${deliveryChallans.length} Delivery Challans.`);

  // 12. Seed Bank Accounts for all Organisations
  const bankAccounts = await BankAccount.insertMany([
    // Org 1 Bank Accounts
    {
      bankName: 'HDFC Bank',
      accountNumber: '50200088921101',
      accountHolderName: 'Smart Enterprise Industries Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'HDFC0000024',
      branchName: 'Guindy Industrial Estate Branch, Chennai',
      accountType: 'CURRENT',
      currentBalance: 4850000,
      isPrimary: true,
      status: 'ACTIVE',
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    {
      bankName: 'State Bank of India',
      accountNumber: '38910022410',
      accountHolderName: 'Smart Enterprise Industries Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'SBIN0000800',
      branchName: 'Chennai Main Commercial Branch',
      accountType: 'CURRENT',
      currentBalance: 2215000,
      isPrimary: false,
      status: 'ACTIVE',
      organisationId: org._id.toString(),
      branchId: branches[0]._id.toString(),
    },
    // Org 2 Bank Accounts
    {
      bankName: 'ICICI Bank',
      accountNumber: '000405118920',
      accountHolderName: 'Smart Nexa Logistics & Supply Chain Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'ICIC0000004',
      branchName: 'BKC Premier Corporate Branch, Mumbai',
      accountType: 'CURRENT',
      currentBalance: 6420000,
      isPrimary: true,
      status: 'ACTIVE',
      organisationId: org2._id.toString(),
      branchId: branches[3]._id.toString(),
    },
    {
      bankName: 'Axis Bank',
      accountNumber: '918020044192801',
      accountHolderName: 'Smart Nexa Logistics & Supply Chain Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'UTIB0000100',
      branchName: 'Nariman Point Corporate Branch, Mumbai',
      accountType: 'CURRENT',
      currentBalance: 1870000,
      isPrimary: false,
      status: 'ACTIVE',
      organisationId: org2._id.toString(),
      branchId: branches[3]._id.toString(),
    },
    // Org 3 Bank Accounts
    {
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '8411099231',
      accountHolderName: 'Smart Apex Electronics & Technologies Pvt. Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'KKBK0000180',
      branchName: 'Electronic City Tech Branch, Bengaluru',
      accountType: 'CURRENT',
      currentBalance: 3980000,
      isPrimary: true,
      status: 'ACTIVE',
      organisationId: org3._id.toString(),
      branchId: branches[6]._id.toString(),
    },
    {
      bankName: 'HDFC Bank',
      accountNumber: '50200099418204',
      accountHolderName: 'Smart Apex Electronics & Technologies Pvt. Ltd.',
      accountHolderType: 'ORGANISATION',
      ifscCode: 'HDFC0000140',
      branchName: 'Koramangala Innovation Branch, Bengaluru',
      accountType: 'CURRENT',
      currentBalance: 1540000,
      isPrimary: false,
      status: 'ACTIVE',
      organisationId: org3._id.toString(),
      branchId: branches[6]._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${bankAccounts.length} Bank Accounts across all organisations.`);

  // 13. Seed Additional Customers for Org 2 & Org 3
  const extraCustomers = await Customer.insertMany([
    // Org 2 Customers
    {
      code: 'CUST-AMZ',
      name: 'Amazon Seller Services India Pvt. Ltd.',
      contactPerson: 'Saurabh Mittal (Logistics Procurement)',
      email: 'saurabh.m@amazon.in',
      phone: '+91 98201 55678',
      address: 'Brigade Gateway, 8th Floor, Malleshwaram, Bengaluru - 560055',
      billingAddress: 'Brigade Gateway, 8th Floor, Malleshwaram, Bengaluru - 560055',
      shippingAddress: 'Amazon Fulfillment Center BOM5, Bhiwandi, Thane - 421302, Maharashtra',
      city: 'Mumbai / Bhiwandi',
      state: 'Maharashtra',
      billingState: 'Karnataka',
      shippingState: 'Maharashtra',
      gstin: '27AAACA1234F1ZA',
      outstandingBalance: 3200000,
      creditLimit: 10000000,
      organisationId: org2._id.toString(),
      branchId: branches[3]._id.toString(),
    },
    {
      code: 'CUST-FK',
      name: 'Flipkart India Private Limited',
      contactPerson: 'Rohan Deshmukh (Supply Chain Manager)',
      email: 'rohan.d@flipkart.com',
      phone: '+91 98203 99881',
      address: 'Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Bengaluru - 560103',
      billingAddress: 'Buildings Alyssa, Embassy Tech Village, Bengaluru - 560103',
      shippingAddress: 'Flipkart Logistics Hub, Farrukhnagar, Gurugram - 122506, Haryana',
      city: 'Delhi-NCR',
      state: 'Delhi',
      billingState: 'Karnataka',
      shippingState: 'Haryana',
      gstin: '07AAACF8990K1Z5',
      outstandingBalance: 1850000,
      creditLimit: 7500000,
      organisationId: org2._id.toString(),
      branchId: branches[4]._id.toString(),
    },
    // Org 3 Customers
    {
      code: 'CUST-FOX',
      name: 'Foxconn India Electronics Pvt. Ltd.',
      contactPerson: 'Chen Wei / Arun Kumar (Fab Quality Lead)',
      email: 'arun.k@foxconn.com',
      phone: '+91 98450 77112',
      address: 'Foxconn Campus, Sri City SEZ, Satyavedu Mandal, Chittoor - 517646, Andhra Pradesh',
      billingAddress: 'Foxconn Campus, Sri City SEZ, Satyavedu Mandal - 517646',
      shippingAddress: 'Inward Warehouse, Assembly Plant 2, Sri City - 517646',
      city: 'Bengaluru / Sri City',
      state: 'Karnataka',
      billingState: 'Andhra Pradesh',
      shippingState: 'Andhra Pradesh',
      gstin: '37AAACF4412B1Z1',
      outstandingBalance: 4200000,
      creditLimit: 15000000,
      organisationId: org3._id.toString(),
      branchId: branches[6]._id.toString(),
    },
    {
      code: 'CUST-DIXON',
      name: 'Dixon Technologies India Ltd.',
      contactPerson: 'Rajesh Mehra (VP Engineering)',
      email: 'rajesh.m@dixoninfo.com',
      phone: '+91 98110 33445',
      address: 'B-14 & 15, Phase-II, Noida - 201305, Uttar Pradesh',
      billingAddress: 'B-14 & 15, Phase-II, Noida - 201305',
      shippingAddress: 'Plant 4, Electronic Zone, Hinjawadi Phase 1, Pune - 411057',
      city: 'Pune',
      state: 'Maharashtra',
      billingState: 'Uttar Pradesh',
      shippingState: 'Maharashtra',
      gstin: '27AAACD9910J1ZV',
      outstandingBalance: 2750000,
      creditLimit: 8000000,
      organisationId: org3._id.toString(),
      branchId: branches[7]._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${extraCustomers.length} Extra Customers for Org 2 & Org 3.`);

  // 14. Seed Products for Org 2 & Org 3
  const extraProducts = await Product.insertMany([
    // Org 2 Products (Logistics & Packaging)
    {
      sku: 'PAL-HD-1200',
      name: 'Heavy Duty Euro Wooden Cargo Pallet 1200x800mm',
      category: 'Logistics Packaging',
      uom: 'Nos',
      hsnCode: '44152000',
      purchaseCost: 850,
      sellingPrice: 1450,
      currentStock: 350,
      minReorderLevel: 50,
      taxRate: 18,
      status: 'ACTIVE',
      approvalStatus: 'Approved',
      organisationId: org2._id.toString(),
    },
    {
      sku: 'GPS-FLT-04',
      name: 'Telematics OBD-II Asset GPS Fleet Tracker',
      category: 'Tracking & IoT',
      uom: 'Nos',
      hsnCode: '85269190',
      purchaseCost: 2200,
      sellingPrice: 4800,
      currentStock: 80,
      minReorderLevel: 20,
      taxRate: 18,
      status: 'ACTIVE',
      approvalStatus: 'Approved',
      organisationId: org2._id.toString(),
    },
    // Org 3 Products (Electronics & Semiconductors)
    {
      sku: 'MCU-ARM-C4',
      name: 'ARM Cortex-M4 32-Bit Microcontroller System Board',
      category: 'Embedded Systems',
      uom: 'Nos',
      hsnCode: '85423100',
      purchaseCost: 1850,
      sellingPrice: 3400,
      currentStock: 620,
      minReorderLevel: 100,
      taxRate: 18,
      status: 'ACTIVE',
      approvalStatus: 'Approved',
      organisationId: org3._id.toString(),
    },
    {
      sku: 'PCB-FR4-8L',
      name: 'Multilayer FR-4 8-Layer High-Frequency PCB Substrate',
      category: 'Bare PCBs',
      uom: 'Nos',
      hsnCode: '85340000',
      purchaseCost: 650,
      sellingPrice: 1250,
      currentStock: 450,
      minReorderLevel: 200,
      taxRate: 18,
      status: 'ACTIVE',
      approvalStatus: 'Approved',
      organisationId: org3._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${extraProducts.length} Extra Products for Org 2 & Org 3.`);

  // 15. Seed Store Items for Org 2 & Org 3
  const extraStoreItems = await StoreItem.insertMany([
    {
      productId: extraProducts[0]._id.toString(),
      productName: extraProducts[0].name,
      sku: extraProducts[0].sku,
      warehouse: 'Mumbai Western Container Terminal',
      binLocation: 'BAY-PAL-01',
      availableStock: 350,
      minLevel: 50,
      maxLevel: 1000,
      lastAudited: '2026-09-05',
      status: 'In Stock',
      branchId: branches[3]._id.toString(),
      organisationId: org2._id.toString(),
    },
    {
      productId: extraProducts[2]._id.toString(),
      productName: extraProducts[2].name,
      sku: extraProducts[2].sku,
      warehouse: 'Bengaluru Fab Cleanroom Vault',
      binLocation: 'CLEAN-A-12',
      availableStock: 620,
      minLevel: 100,
      maxLevel: 2000,
      lastAudited: '2026-09-08',
      status: 'In Stock',
      branchId: branches[6]._id.toString(),
      organisationId: org3._id.toString(),
    },
  ]);
  console.log(`✔ Seeded ${extraStoreItems.length} Extra Store Items for Org 2 & Org 3.`);

  console.log('\n==========================================');
  console.log('🎉 ALL BACKEND ERP DATA SEEDED INTO MONGODB ATLAS WITH MULTI-TENANT & BRANCH SCOPING!');
  console.log('==========================================\n');
}

if (require.main === module) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seeding failed:', err);
      process.exit(1);
    });
}
